[package]
name = "star_stuff"
version = "0.0.0"

[dependencies]
regex = "*"
rayon = "*"
itertools = "*"
docopt = "*"
rustc-serialize = "*"
image = { path = "../image" }
convert = { path = "../convert" }
geom = { path = "../geom" }
num = "*"
