[package]
name = "star_aligner"
version = "0.1.0"

[dependencies]
log = "*"
sextractor = { path = "../sextractor" }
geom = { path = "../geom" }
imagemagick = { path = "../imagemagick" }
simd = "*"
#ndarray = "*"
#ndarray-linalg = "*"
rulinalg = "*"

[dev-dependencies]
serde = "*"
serde_json = "*"
