[package]
name = "star_aligner"
version = "0.1.0"

[dependencies]
sextractor = { path = "../sextractor" }
geom = { path = "../geom" }
imagemagick = { path = "../imagemagick" }
simd = "*"

[dev-dependencies]
serde = "*"
serde_json = "*"
