[package]
name = "sieve"
version = "0.1.0"

[dependencies]
log = "*"
env_logger = "*"
rand = "*"
iron = "0.4"
staticfile = "*"
mount = "0.2"
router = "0.4"
serde_json = "*"
logger = "*"
persistent = "0.2"
docopt = "*"
rustc-serialize = "*"
