#!/usr/bin/env python3

import io
import sys
from subprocess import run, PIPE
from donuts import Donuts

reference_image_name = sys.argv[1]
science_image_name = sys.argv[2]

def to_fits(src):
  d = run([
  "convert",
      f"jpeg:{src}",
      "-gravity","center",
      "-extent","2000x2000",
      "-crop","2000x2000",
      "-depth","16",
      "-set","colorspace","Gray",
      "-separate",
      "-average",
      f"fits:-",
  ], check=True, stdout=PIPE).stdout
  return io.BytesIO(d)

reference_image_name = to_fits(reference_image_name)
science_image_name = to_fits(science_image_name)

# Construct a donuts object
d = Donuts(
  refimage=reference_image_name,
  image_ext=0,
  overscan_width=20,
  prescan_width=20,
  border=64,
  normalise=True,
  #exposure='EXPOSURE',
  subtract_bkg=True,
  ntiles=32)

shift_result = d.measure_shift(science_image_name)
x = shift_result.x.value
y = shift_result.y.value
print(f'{x},{y}')
