[package]
name = "sieve"
version = "0.1.0"

[dependencies]
structopt = "*"
structopt-derive = "*"
log = "*"
env_logger = "*"
rand = "*"
iron = "0.4"
staticfile = "0.3"
mount = "0.2"
router = "0.4"
serde_json = "*"
logger = "0.2"
persistent = "0.2"
