[package]
name = "align"
version = "0.1.0"

[dependencies]
structopt = "*"
structopt-derive = "*"
log = "*"
env_logger = "*"
image = { path = "../image" }
donuts = { path = "../donuts" }
star_aligner = { path = "../star_aligner" }
align_api = { path = "../align-api" }
rayon = "*"
tempfile = "*"
