[package]
name = "image"
version = "0.0.0"

[dependencies]
convert = { path = "../convert" }
imagemagick = { path = "../imagemagick" }
fits = { path = "../fits" }
regex = "*"
turbojpeg = { path = "../../turbojpeg-rs" }
rand = "*"
byteorder = "*"
quickersort = "*"
num = "*"
